BASE: ['']
TOOLBOX_MODE: "train_and_test" # "train_and_test"  or "only_test"
TRAIN:
  BATCH_SIZE: 4
  EPOCHS: 100
  LR: 1e-3
  WEIGHT_DECAY: 0.00005	
  STRP_SIZE: 50   	# lr 优化器参数
  GAMMA: 0.5     	# lr 优化器参数
  A_START: 0.1
  B_START: 1.0
  EXP_A: 0.5
  EXP_B: 5.0		# a --> Pearson loss; b --> frequency loss
  MODEL_FILE_NAME: UBFC_UBFC_UBFC_physformer_stan  # 训练集-验证集-测试集-网络-修改程度
  DATA:
    FS: 30
    DATASET: UBFC
    DO_PREPROCESS: FALSE            # if first time, should be true
    DATA_FORMAT: NCDHW
    DATA_PATH: "/data/chushuyang/UBFC_RAW/"                     # Raw dataset path, need to be updated
    CACHED_PATH: "/data/chushuyang/rPPG_Toolbox/UBFC_Processed/"    # Processed dataset save path, need to be updated
    FILE_LIST_PATH: "/home/chushuyang/research/rPPG-Toolbox/ckpt/DataFileLists/"    # Path to store file lists, needs to be updated
    EXP_DATA_NAME: ""
    BEGIN: 0.0
    END: 0.6
    PREPROCESS :
      DATA_TYPE: ['Normalized'] #if use physnet, should be Normalized
      LABEL_TYPE: Normalized
      DO_CHUNK: True
      CHUNK_LENGTH: 128  #only support for factor of 512
      DYNAMIC_DETECTION: False
      DYNAMIC_DETECTION_FREQUENCY : 128
      CROP_FACE: True
      LARGE_FACE_BOX: True
      LARGE_BOX_COEF: 1.5
      H: 128
      W: 128
VALID:
  DATA:
    FS: 30
    DATASET: UBFC
    DO_PREPROCESS: FALSE                # if first time, should be true
    DATA_FORMAT: NCDHW
    DATA_PATH: "/data/chushuyang/UBFC_RAW/"                     # Raw dataset path, need to be updated
    CACHED_PATH: "/data/chushuyang/rPPG_Toolbox/UBFC_Processed/"    # Processed dataset save path, need to be updated
    FILE_LIST_PATH: "/home/chushuyang/research/rPPG-Toolbox/ckpt/DataFileLists/"    # Path to store file lists, needs to be updated
    EXP_DATA_NAME: ""
    BEGIN: 0.6
    END: 0.8
    PREPROCESS :
      DATA_TYPE: ['Normalized'] #if use physnet, should be Normalized
      LABEL_TYPE: Normalized
      DO_CHUNK: True
      CHUNK_LENGTH: 128  #only support for factor of 512
      DYNAMIC_DETECTION: False
      DYNAMIC_DETECTION_FREQUENCY : 128
      CROP_FACE: True
      LARGE_FACE_BOX: True
      LARGE_BOX_COEF: 1.5
      H: 128
      W: 128
TEST:
  METRICS: ['MAE','RMSE','MAPE','Pearson']
  DATA:
    FS: 30
    DATASET: UBFC
    DO_PREPROCESS: FALSE                  # if first time, should be true
    DATA_FORMAT: NCDHW
    DATA_PATH: "/data/chushuyang/UBFC_RAW/"                     # Raw dataset path, need to be updated
    CACHED_PATH: "/data/chushuyang/rPPG_Toolbox/UBFC_Processed/"    # Processed dataset save path, need to be updated
    FILE_LIST_PATH: "/home/chushuyang/research/rPPG-Toolbox/ckpt/DataFileLists/"    # Path to store file lists, needs to be updated
    EXP_DATA_NAME: ""
    BEGIN: 0.8
    END: 1.0
    PREPROCESS :
      DATA_TYPE: ['Normalized'] #if use physnet, should be Normalized
      LABEL_TYPE: Normalized
      DO_CHUNK: True
      CHUNK_LENGTH: 128  #only support for factor of 512
      DYNAMIC_DETECTION: False
      DYNAMIC_DETECTION_FREQUENCY : 128
      CROP_FACE: True
      LARGE_FACE_BOX: True
      LARGE_BOX_COEF: 1.5
      H: 128
      W: 128
DEVICE: cuda:6
NUM_OF_GPU_TRAIN: 1
LOG:
  PATH: runs/exp
MODEL:
  DROP_RATE: 0.2
  NAME: Physnet
  PHYSNET:
    FRAME_NUM: 128
INFERENCE:
  BATCH_SIZE: 4
  EVALUATION_METHOD: FFT        # "FFT" or "peak detection"
  MODEL_PATH: ""            # 仅在 test mode 下需要输入，意义为 .pth 文件的路径
